### ISSUE TITLE
Problems met when installing data-over-dab-example

### ISSUE THREAD

**Issue by cwhuang913** [Opendigitalradio/data-over-dab-example#1]
I met 2 problems when installing data-over-dab-example.
Could anybody give me some advices?
Thanks a lot.

joseph@Joseph-Kubuntu:~/ODR-MMB-Tools/data-over-dab-example/build$ cmake --build .
Scanning dependencies of target dabdemod
[  3%] Building CXX object external/dabdemod/src/CMakeFiles/dabdemod.dir/demodulator.cpp.o
[  6%] Building CXX object external/dabdemod/src/CMakeFiles/dabdemod.dir/util/fft.cpp.o
[  9%] Building CXX object external/dabdemod/src/CMakeFiles/dabdemod.dir/util/phase_reference.cpp.o
[ 12%] Building CXX object external/dabdemod/src/CMakeFiles/dabdemod.dir/util/symbol_handler.cpp.o
[ 16%] Building CXX object external/dabdemod/src/CMakeFiles/dabdemod.dir/util/deinterleaver.cpp.o
[ 19%] Linking CXX static library ../../../lib/libdabdemod.a
[ 19%] Built target dabdemod
Scanning dependencies of target dabdecode
[ 22%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/ensemble/ensemble.cpp.o
[ 25%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/ensemble/service.cpp.o
[ 29%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/ensemble/service_component.cpp.o
[ 32%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/ensemble/subchannel.cpp.o
[ 35%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/frame/cif.cpp.o
[ 38%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/frame/fib.cpp.o
[ 41%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/frame/frame.cpp.o
[ 45%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/parser/fic_parser.cpp.o
[ 48%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/parser/fic_parser_fig_0.cpp.o
[ 51%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/parser/fic_parser_fig_1.cpp.o
[ 54%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/viterbi/calc_metric.cpp.o
[ 58%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/viterbi/core_algorithms.cpp.o
[ 61%] Building CXX object external/dabdecode/src/CMakeFiles/dabdecode.dir/viterbi/fsm.cpp.o
[ 64%] Linking CXX static library ../../../lib/libdabdecode.a
[ 64%] Built target dabdecode
Scanning dependencies of target dabip
[ 67%] Building CXX object external/dabip/src/CMakeFiles/dabip.dir/util/crc16.cpp.o
[ 70%] Building CXX object external/dabip/src/CMakeFiles/dabip.dir/packet/packet_generator.cpp.o
[ 74%] Building CXX object external/dabip/src/CMakeFiles/dabip.dir/packet/packet_parser.cpp.o
[ 77%] Building CXX object external/dabip/src/CMakeFiles/dabip.dir/msc_data_group/msc_data_group_generator.cpp.o
[ 80%] Building CXX object external/dabip/src/CMakeFiles/dabip.dir/msc_data_group/msc_data_group_parser.cpp.o
[ 83%] Linking CXX static library ../../../lib/libdabip.a
[ 83%] Built target dabip
Scanning dependencies of target packager
[ 87%] Building CXX object src/CMakeFiles/packager.dir/packager.cpp.o
[ 90%] Linking CXX executable ../products/bin/packager
[ 90%] Built target packager
Scanning dependencies of target receiver
[ 93%] Building CXX object src/CMakeFiles/receiver.dir/receiver.cpp.o
/home/joseph/ODR-MMB-Tools/data-over-dab-example/src/receiver.cpp: In function ‘int main(int, char**)’:
/home/joseph/ODR-MMB-Tools/data-over-dab-example/src/receiver.cpp:111:65: error: use of deleted function ‘dab::ensemble::ensemble(dab::ensemble&&)’
   auto ensemble = dab::ensemble{symbols, dab::kTransmissionMode1};
                                                                 ^
In file included from /home/joseph/ODR-MMB-Tools/data-over-dab-example/src/receiver.cpp:36:0:
/home/joseph/ODR-MMB-Tools/data-over-dab-example/external/dabdecode/include/dab/ensemble/ensemble.h:68:10: note: ‘dab::ensemble::ensemble(dab::ensemble&&)’ is implicitly deleted because the default definition would be ill-formed:
   struct ensemble
          ^~~~~~~~
/home/joseph/ODR-MMB-Tools/data-over-dab-example/external/dabdecode/include/dab/ensemble/ensemble.h:68:10: error: use of deleted function ‘std::atomic<bool>::atomic(const std::atomic<bool>&)’
In file included from /usr/include/asio/detail/atomic_count.hpp:23:0,
                 from /usr/include/asio/detail/task_io_service.hpp:24,
                 from /usr/include/asio/impl/io_service.hpp:69,
                 from /usr/include/asio/io_service.hpp:765,
                 from /home/joseph/ODR-MMB-Tools/data-over-dab-example/include/tun_device.h:45,
                 from /home/joseph/ODR-MMB-Tools/data-over-dab-example/src/receiver.cpp:32:
/usr/include/c++/7/atomic:71:5: note: declared here
     atomic(const atomic&) = delete;
     ^~~~~~
src/CMakeFiles/receiver.dir/build.make:62: recipe for target 'src/CMakeFiles/receiver.dir/receiver.cpp.o' failed
make[2]: *** [src/CMakeFiles/receiver.dir/receiver.cpp.o] Error 1
CMakeFiles/Makefile2:667: recipe for target 'src/CMakeFiles/receiver.dir/all' failed
make[1]: *** [src/CMakeFiles/receiver.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mpbraendli** [comment]
@fmorgner do you have an idea what fails?

**Comment by mpbraendli** [comment]
@fmorgner ping

**Comment by mpbraendli** [comment]
Close because data-over-dab-example is unmaintained. Try https://github.com/Opendigitalradio/data-injector instead.
